---
namespace:              science.climatology.ncdc
protocol:               weather

data_asset:
- name:                 ncdc_data_asset
  location:             ncdc_data.tsv
  type:                 ncdc_data_record

targets:
  catalog:
  - name:               ncdc_catalog_entry
    title:              The display title of this catalog entry
    description: -|
      A very detailed description of the entry goes here. Ensure proper formatting and clear concise information about the dataset as this field will be the main visibility point of the dataset page.
    tags:
    - an
    - array
    - of
    - single-word
    - tags
    packages:
    - data_assets:
      - ncdc_data_asset

types:
- name: ncdc_data_record
  type: record
  doc: Description of the ncdc_data_record type
  fields:
  - name: A name for one of the fields in the ncdc_data_record type
    doc: A description for this field
    type: If this not a primitive type, make sure you explicitly define it below
  - name: A name for one of the fields in the ncdc_data_record type
    doc: A description for this field
    type: If this not a primitive type, make sure you explicitly define it below
