---
namespace: social.network.ok_cupid
protocol: politics_question

data_assets:
- name: politics_question_asset
  location: politics_question_data.tsv
  type: politics_question_record
  
targets:
  catalog:
  - name: politics_question_catalog_entry
    title: Ok Cupid Describe yourself politically
    description: -|
    The data contains answers to the OkCupid question of "How would you describe yourself politically?". Provided are the frequency of responses to each of the possible answers, Liberal, Centrist, Conservative, None Of The Above, based on location (state, city, or metropolitan statistical area (MSA)), age group, and gender.  
    tags:
    - politics
    - dating
    - voting
    - political_sentiment
    - democrat
    - republican
    - liberal
    - social_network
    packages: # You only need this if your dataset will be available for bulk download
    - data_assets:
      - politics_question_data_asset

# Any non-basic types declared above must be defined explicitly under this type heading
types:
- name: politics_question_data_record
  type: record
  doc: Description of the politics_question_data_record type
  fields:
  - name: A name for one of the fields in the politics_question_data_record type
    doc: A description for this field
    type: If this not a primitive type, make sure you explicitly define it below
  - name: A name for one of the fields in the politics_question_data_record type
    doc: A description for this field
    type: If this not a primitive type, make sure you explicitly define it below
    

