---
namespace: social.network.ok_cupid
protocol: politics_question

data_assets:
- name: politics_question_asset
  location: politics_question_data.tsv
  type: politics_question_record
  
code_assets:
- name: politics_question_asset
  location: code/politics_question_endpoint.rb

messages:
  lookup:
    response: 
    doc: 
    initial_free_qty: 
    price_per_k_in_cents: 
    request:
    - name: 
      type: 
    samples:
    - request:
      - game_id: 
         innning: 
  

targets:
  catalog:
  - name: politics_question_catalog_entry
    title: OkCupid Political Sentiment API
    description: -|
    The data is derived from the OkCupid question, "How would you describe yourself politically?". 
Provided are the frequency of responses to each of the possible answers, Liberal, Centrist, 
Conservative, None Of The Above. In addition, the data provides the location (state, city, 
or metropolitan statistical area (MSA)), age group, and gender of the participants. With the data
combined one could gain a very insightful understanding of an area's political makeup. OkCupid 
is a popular free online dating site, recently purchased by Match.com.  

h3. OkCupid Political Sentiment Use Cases

* Discover Trends in Geographic Areas
* Make political comparisons in answers by age, gender, and other demographic details
    tags:
    - politics
    - dating
    - voting
    - political_sentiment
    - democrat
    - republican
    - liberal
    - social_network
    packages: # You only need this if your dataset will be available for bulk download
    - data_assets:
      - politics_question_data_asset

# Any non-basic types declared above must be defined explicitly under this type heading
types:
- name: politics_question_data_record
  type: record
  doc: Description of the politics_question_data_record type
  fields:
  - name: A name for one of the fields in the politics_question_data_record type
    doc: A description for this field
    type: If this not a primitive type, make sure you explicitly define it below
  - name: A name for one of the fields in the politics_question_data_record type
    doc: A description for this field
    type: If this not a primitive type, make sure you explicitly define it below
    

