--- 
messages: 
  team_standings: 
    response: team_standings_record
    doc: Get a team's W-L record
    request: 
    - name: team_standings_request
      type: team_standings_request
data_assets: 
- name: team_standings_data_asset
  location: data/team_standings
  type: team_standings_record
namespace: sports.stats.baseball
code_assets: 
- name: pennant_endpoint
  location: code/pennant_endpoint.rb
protocol: pennant
targets: 
  mysql: 
  - name: baseball_pennant
    data_assets: 
    - team_standings_data_asset
    database: sports_stats_baseball
    table_name: pennant_team_standings
  catalog: 
  - name: baseball_pennant
    messages: 
    - team_standings
    title: Stats from Pennant data
    tags: 
    - sports
    - stats
    - baseball
    - win-loss
    description: Pennant data stats
  apeyeye: 
  - code_assets: 
    - pennant_endpoint
types: 
- name: team_standings_request
  doc: Query api parameters for the team_standings message
  fields: 
  - name: team_name
    default: Detroit
    type: string
  - name: record_year
    default: 2010
    type: int
  type: record
- name: team_standings_record
  doc: Team info, year, wins, losses
  fields: 
  - name: team_id
    doc: Team ID
    type: string
  - name: team_city
    doc: Team city
    type: string
  - name: team_name
    doc: Team name
    type: string
  - name: record_year
    doc: Year of record
    type: int
  - name: record_wins
    doc: Wins for the year
    type: int
  - name: record_losses
    doc: Losses for the year
    type: int
  type: record
