data_assets: 
- name: data_gov_au_data_asset
  location: data/name_of_dataset.tsv
under_consideration: true
update_frequency: monthly

targets: 
  catalog: 
  - name: data_gov_au_entry
    title: Name Of Dataset Entry from data.gov.au
    tags: 
    - tags
    description: |-
      DESCDESCDESC
    packages:
    - data_assets:
      - data_gov_au_data_asset
