data_assets: 
- name: data_gov_au_data_asset
  location: catalog.yaml
  type: 
under_consideration: "true"
targets: 
  catalog: 
  - name: data_gov_au_catalog
    messages: 
    - places
    title: Data.gov.au Catalog
    tags: 
    - government
    - datasets
    - 
    description: |-
      A list of all datasets available from Data.gov.au, with a link to download it from their servers as well as metadata like description, data size, and tags.