data_assets: 
- name: data_gov_au_data_asset
  location: data/name_of_dataset.tsv
under_consideration: true
update_frequency: monthly

targets: 
  catalog: 
  - name: data_gov_au_entry
    title: Name Of Dataset Entry from Data.gov.au
    tags: 
    - tags
    - from
    - indivudual
    - dataset
    - metadata
    description: |-
      A dataset from Data.gov.au, with the following metadata:
      * Size: if applicable
      * Type: if applicable
      * Desc: if applicable
      * Sexy: Yes, definitely
    packages:
    - data_assets:
      - data_gov_au_data_asset
