---
namespace: sports.baseball.vargatron
protocol: season_stats
under_consideration: true
data_assets:
- name: season_stats_data_asset
  location: data/season_stats.json
  type: season_record
code_assets:
- name: season_stats_code
  location: code/season_stats_endpoint.rb
messages:
  lookup:
    response: season_record
    doc: Get detailed records for a specific team's season.
    request:
    - name: season_stats_lookup_request
      type: season_stats_lookup_request
    samples:
    - request:
      - team_id: TEX
        season: 2010
targets:
  catalog:
  - name: season_stats_catalog_entry
    title: Pennant Baseball Seasons (1960-2010)
    description: |-
      Take me out to the ball game! Get game_ids and see team season statistics like win, losses, RBIs, OBP, ERA,and many more. Get both the absolute values and percentiles related to the rest of the league. Plug the game_id into the Pennant Baseball Game Logs API to get at bat data.

      To find individual season statistics just enter the team_id and year. You can get the team_id and year from the Pennant Baseball History API. You can also use this API in concert with Pennant Baseball History to get a list of all available seasons and team_ids.

      Are you an app developer? Use the API to build captivating visualizations or to recap your favorite seasons.
      Fancy yourself a statistician? Use this data to glean new insights about your favorite teams.

      The first 5,000 calls per month for this data are free. After the first 5,000, the calls are $5 per 1,000 calls. At the end of every month, we will tally your usage and bill your credit card. Any calls to any Pennant data will be included in this total. This data is considered a Premium Data Set, and only Brass Monkey customers or higher will be able to use it. We offer a 14 day trial for any new Brass monkey sign up, that allows you to play with the data for free up to the 5,000 call limit.
      Note that while Pennant's Baseball Seasons is a paid API, the supplier is making it free for not for profit and educational purposes. Contact Infochimps to let us know what you plan to do with the API and to see if you qualify for free access.
    tags:
    - sports
    - baseball
    - stats
    - statistics
    - more-tags-please
    messages:
    - lookup
types:

- name: season_stats_lookup_request
  doc: Query API parameters for the season_record lookup message.
  type: record
  fields:
  - name: team_id
    type: string
  - name: season
    type: string

- name: season_record
  type: record
  doc: All of the team's records for a specific season.
  fields:
  - name: season
    doc: Year of the season.
    type: string
  - name: team_id
    doc: Uppercase 3-letter team identifier. When a team moves, it gets a new id.
    type: string
  - name: team_name 
    doc: The team's name.
    type: string
  - name: team_location
    doc: The team location, generally a city or state.
    type: string  - name: primary_color
    doc: The team's primary color's name.
    type: string
  - name: secondary_color
    doc: The team's secondary color's name.
    type: string
  - name: primary_color_hex
    doc: The team's primary color's hexadecimal code.
    type: string
  - name: secondary_color_hex
    doc: The team's secondary color's hexadecimal code.
    type: string
  - name: home_stadium
    doc: The team's home stadium during this season.
    type: string
  - name: league
    doc: The team's two-letter uppercase league identifier for this season.
    type: string
  - name: division
    doc: The team's one-letter uppercase division identifier for this season.
    type: string
  - name: league_rank
    doc: This team's ranking out of its league for this season.
    type: int
  - name: division_rank
    doc: This team's ranking out of its division for this season.
    type: int
  - name: DS
    doc: PROD Division wins?
    type: int
  - name: LS
    doc: PROD League wins?
    type: int
  - name: WS
    doc: PROD World Series wins?
    type: int
  - name: W
    doc: Total wins this season.
    type: int
  - name: L
    doc: Total losses this season.
    type: int
  - name: R
    doc: Total runs this season.
    type: int
  - name: AB
    doc: Total at-bats this season.
    type: int
  - name: BA
    doc: Total batting average this season.
    type: float
  - name: OBP
    doc: Total on base percentage this season.
    type: float
  - name: H
    doc: Total hits this season.
    type: int
  - name: DBL
    doc: Total doubles this season.
    type: int
  - name: TPL
    doc: Total triples this season.
    type: int
  - name: HR
    doc: Total home runs this season.
    type: int
  - name: BB
    doc: Total walks this season.
    type: int
  - name: SB
    doc: Total stolen bases this season.
    type: int
  - name: SO
    doc: Total strikeouts this season.
    type: int
  - name: CS
    doc: Total caught stealing this season.
    type: int
  - name: HBP
    doc: Total hit by pitcher this season.
    type: int
  - name: SF
    doc: Total sacrifice flies this season.
    type: int
  - name: RA
    doc: Total PROD this season.
    type: int
  - name: ER
    doc: Total PROD this season.
    type: int
  - name: ERA
    doc: Total earned run average this season.
    type: float
  - name: CG
    doc: Total complete games this season.
    type: int
  - name: SHO
    doc: Total shutouts this season.
    type: int
  - name: SV
    doc: Total saves this season.
    type: int
  - name: IPouts
    doc: Total PROD this season.
    type: int
  - name: HA
    doc: Total hits against this season.
    type: int
  - name: HRA
    doc: Total home runs against this season.
    type: int
  - name: BBA
    doc: Total walks against this season.
    type: int
  - name: SOA
    doc: Total strikeouts against this season.
    type: int
  - name: E
    doc: Total errors this season.
    type: int
  - name: DP
    doc: Total PROD this season.
    type: int
  - name: FP
    doc: Total fielding percentage this season.
    type: float
  - name: relative_W
    doc: League percentile for wins this season.
    type: float
  - name: relative_L
    doc: League percentile for losses this season.
    type: float
  - name: relative_R
    doc: League percentile for runs this season.
    type: float
  - name: relative_AB
    doc: League percentile for at-bats this season.
    type: float
  - name: relative_BA
    doc: League percentile for batting average this season.
    type: float
  - name: relative_OBP
    doc: League percentile for on base percentage this season.
    type: float
  - name: relative_H
    doc: League percentile for hits this season.
    type: float
  - name: relative_DBL
    doc: League percentile for doubles this season.
    type: float
  - name: relative_TPL
    doc: League percentile for triples this season.
    type: float
  - name: relative_HR
    doc: League percentile for home runs this season.
    type: float
  - name: relative_BB
    doc: League percentile for walks this season.
    type: float
  - name: relative_SB
    doc: League percentile for stolen bases this season.
    type: float
  - name: relative_SO
    doc: League percentile for strikeouts this season.
    type: float
  - name: relative_CS
    doc: League percentile for caught stealing this season.
    type: float
  - name: relative_HBP
    doc: League percentile for hit by pitcher this season.
    type: float
  - name: relative_SF
    doc: League percentile for sacrifice flies this season.
    type: float
  - name: relative_RA
    doc: League percentile for PROD this season.
    type: float
  - name: relative_ER
    doc: League percentile for PROD this season.
    type: float
  - name: relative_ERA
    doc: League percentile for earned run average this season.
    type: float
  - name: relative_CG
    doc: League percentile for complete games this season.
    type: float
  - name: relative_SHO
    doc: League percentile for shutouts this season.
    type: float
  - name: relative_SV
    doc: League percentile for saves this season.
    type: float
  - name: relative_IPouts
    doc: League percentile for PROD this season.
    type: float
  - name: relative_HA
    doc: League percentile for hits against this season.
    type: float
  - name: relative_HRA
    doc: League percentile for home runs against this season.
    type: float
  - name: relative_BBA
    doc: League percentile for walks against this season.
    type: float
  - name: relative_SOA
    doc: League percentile for strikeouts against this season.
    type: float
  - name: relative_E
    doc: League percentile for errors this season.
    type: float
  - name: relative_DP
    doc: League percentile for PROD this season.
    type: float
  - name: relative_FP
    doc: League percentile for fielding percentage this season.
    type: float
  - name: regular_season_games
    doc: List of all games played this season, including dates, score, opponent's score, and result. Much more data is included in the Pennant Baseball Game Logs API, accessed using the game's stadium's team_id and date.
    type:
      type: array
      items: game_record
  - name: post_season_games
    doc: List of all games played during the postseason, including game_ids, dates, score, opponent's score, and result. Much more data is included in the Pennant Baseball Game Logs API, accessed using the game's stadium's team_id and date.
    type:
      type: array
      items: game_record

- name: game_record
  type: record
  doc: The game_id, date, score, opponent's score, and result for a specific game. Much more data is included in the Pennant Baseball Game Logs API, accessed using the game_id.
  fields:
  - name: date
    doc: The date of the game. The date's format is "AAAABBCCD". AAAA is the four-digit number of the year. BB is the two-digit number of the month. CC is the two-digit number of the day. E is the number of the game that day beginning at 0- so it's 0 for most games, 1 for the second game of a double-header, and so on.
    type: string
  - name: game_type
    doc: Whether the game was 'home' or 'away'.
    type: string
  - name: opponent
    doc: The three-letter uppercase id for the opposing team.
    type: string
  - name: home_score
    doc: The number of points the home team scored.
    type: int
  - name: away_score
    doc: The number of points the away team scored.
    type: int
  - name: result
    doc: Whether the game was a win ("W") or a loss ("L").
    type: string
  - name: double_header
    doc: Whether or not this game was part of a double-header. Will be 'true' or 'false'.
    type: string 
