---
namespace: sports.baseball.vargatron
protocol: team_stats
under_consideration: true

data_assets:
- name: team_stats_data_asset
  location: data/team_stats_data.json
  type: team_record

code_assets:
- name: team_stats_code
  location: code/team_stats_endpoint.rb

messages:
  search:
    response: es_response
    doc: Get a team's team_id, list of years played, W-L records, and more.
    request:
    - name: team_stats_search_request
      type: team_stats_search_request
    samples:
    - request:
      - team_name: Rangers

targets:

  catalog:
  - name: team_stats_catalog_entry
    title: Pennant Baseball History (1952-2010)
    description: |-
      
      Batter up! Enter an MLB team name and in return get its team_id and a list of the years played, between 1960-2010.

      Partner this API with the Pennant Baseball Seasons API and get back team statistics, records, and game_ids. Use game_ids with the Pennant Baseball Game Logs API to get full at-bat data.

    tags:
    - sports
    - baseball
    - stats
    - statistics
    messages:
    - search

  elastic_search:
  - index_name: sports.baseball.vargatron
    object_type: team_record
    id_field: team_id
    loader: json_loader
    data_assets:
    - team_stats_data_asset 
    
types:
- name: team_stats_search_request
  doc: Query API parameters for the team_record search message.
  type: record
  fields:
  - name: team_name
    type: string
    doc: A team's name or location.
  - name: _limit
    type: int
    doc: An integer limit to the number of pages returned.
  - name: _from
    type: int
    doc: Integer offset to start @results@ at. A multiple of 10.

- name: year_record
  type: record
  doc: A year record contains the year, the number of wins, the number of losses, and the league.
  fields:
  - name: year
    doc: The year for this record.
    type: int
  - name: wins
    doc: Number of wins this year.
    type: int
  - name: losses
    doc: Number of losses this year.
    type: int
  - name: league
    doc: Uppercase two-letter league identifier.
    type: string

- name: team_record
  type: record
  doc: A team record contains a team's id, colors, league, years played, and win-loss records for those years.
  fields:
  - name: team_id
    doc: Uppercase 3-letter team identifier. When a team moves, it gets a new id.
    type: string
  - name: team_loc
    doc: The team location, generally a city or state.
    type: string
  - name: team_name 
    doc: The team's name.
    type: string
  - name: year_records
    doc: A list of all the years that the team played, with wins, losses, and league for each year.
    type:
      type: array
      items: year_record
  - name: pri_color
    doc: The team's primary color's name.
    type: string
  - name: sec_color
    doc: The team's secondary color's name.
    type: string
  - name: pri_color_hex
    doc: The team's primary color's hexadecimal code.
    type: string
  - name: sec_color_hex
    doc: The team's secondary color's hexadecimal code.
    type: string
    
- name: es_response
  type: record
  doc: A json object containing the total number of records that matched the search as well as an array of @results@.
  fields:
    - name: total
      type: int
      doc: Total number of records that match @team_name@
    - name: results
      doc: A json array of team_records matching @team_name@
      type:
        type: array
        items: team_record
