---
namespace: sports.baseball.vargatron
protocol: team_stats

data_assets:
- name: team_stats_data_asset
  location: data/team_stats.json
  type: team_record

code_assets:
- name: team_stats_code
  location: code/team_stats_endpoint.rb

messages:
  search:
    response: es_response
    doc: Get a team's id, list of seasons played, W-L records, and more.
    initial_free_qty: 5000
    price_per_k_in_cents: 500
    request:
    - name: team_stats_search_request
      type: team_stats_search_request
    samples:
    - request:
      - team_name: Rangers

targets:

  catalog:
  - name: team_stats_catalog_entry
    title: "MLB Baseball API: Team Statistics (1952-2010)"
    description: |-
      Batter up! Enter a MLB team name and in return get back wins, losses, current team colors, seasons played, final regular season standings, home stadium, and team_ids for 1952-2010.

      Grab the team_ids from this API and input them into the "MLB Baseball API: Season Statistics":http://www.infochimps.com/datasets/MLB-Baseball-API-Season-Statistics-1952-2010 to get back detailed team statistics, records, and game_ids. Use game_ids with the "MLB Baseball Game Logs API":http://www.infochimps.com/datasets/MLB-Baseball-API-Game-Logs-1952-2010 to get attendance, box scores, and statistics.

      Click "here":http://www.infochimps.com/datasets/mlb-baseball-api-team-statistics-1952-2010#api-docs_tab to see the full list of statistics.

      There is a one-time free trial of up to 5000 calls. After the first 5,000 calls, the calls are $5 per 1,000 calls. At the end of every month, we will tally your usage and bill your credit card. Any calls to any Pennant data will be included in this total. This data is considered a Premium Data Set, and only Brass Monkey customers or higher will be able to use it. We offer a 14 day trial for any new Brass monkey sign up, that allows you to play with the data for free up to the 5,000 call limit.

      Note: While MLB Baseball API: Team Statistics (1952-2010) is a paid API, the supplier is making it free for not for profit and educational purposes. Contact Infochimps to let us know what you plan to do with the API and to see if you qualify for free access.
    tags:
    - sports
    - baseball
    - stats
    - statistics
    messages:
    - search

  elastic_search:
  - index_name: sports.baseball.vargatron
    object_type: team_record
    id_field: team_id
    loader: json_loader
    data_assets:
    - team_stats_data_asset 

  apeyeye:
  - code_assets:
    - team_stats_code_asset
  
    
types:
- name: team_stats_search_request
  doc: Query API parameters for the team_record search message.
  type: record
  fields:
  - name: team_name
    type: string
    doc: A team's name or location.
  - name: _limit
    type: int
    doc: An integer limit to the number of pages returned.
  - name: _from
    type: int
    doc: Integer offset to start @results@ at. A multiple of 10.

- name: season_record
  type: record
  doc: A season record contains the year, the number of wins, the number of losses, and the league.
  fields:
  - name: season
    doc: The year for this season.
    type: int
  - name: wins
    doc: Number of wins this season.
    type: int
  - name: losses
    doc: Number of losses this season.
    type: int
  - name: division_series
    doc: Number of division series wins this season.
    type: int
  - name: league_rank
    doc: This team's league ranking for this season.
    type: int
  - name: division_rank
    doc: This team's division ranking for this season.
    type: int

- name: team_record
  type: record
  doc: |-
    A team record contains a team's id, current colors, league, division and home stadium.
    It also containes seasons played, and win-loss records for those seasons.
  fields:
  - name: team_id
    doc: Uppercase 3-letter team identifier. When a team moves, it gets a new id.
    type: string
  - name: team_location
    doc: The team location, generally a city or state.
    type: string
  - name: team_name 
    doc: The team's name.
    type: string
  - name: primary_color
    doc: The team's primary color's name.
    type: string
  - name: secondary_color
    doc: The team's secondary color's name.
    type: string
  - name: primary_color_hex
    doc: The team's primary color's hexadecimal code.
    type: string
  - name: secondary_color_hex
    doc: The team's secondary color's hexadecimal code.
    type: string
  - name: home_stadium
    doc: The team's home stadium during its most recent season. Previous stadiums can be found using the Pennant Baseball Seasons API.
    type: string
  - name: league
    doc: The team's two-letter uppercase league identifier for its most recent season.
    type: string
  - name: division
    doc: The team's one-letter uppercase division identifier for its most recent season.
    type: string
  - name: seasons
    doc: A list of all the seasons that the team played, with wins, losses, division series, division rank, and league rank for each season.
    type:
      type: array
      items: season_record
    
- name: es_response
  type: record
  doc: A json object containing the total number of records that matched the search as well as an array of @results@.
  fields:
    - name: total
      type: int
      doc: Total number of records that match @team_name@
    - name: results
      doc: A json array of team_records matching @team_name@
      type:
        type: array
        items: team_record
